// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Synapse) DeepCopyInto(out *Synapse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Synapse.
func (in *Synapse) DeepCopy() *Synapse {
	if in == nil {
		return nil
	}
	out := new(Synapse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Synapse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseList) DeepCopyInto(out *SynapseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Synapse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseList.
func (in *SynapseList) DeepCopy() *SynapseList {
	if in == nil {
		return nil
	}
	out := new(SynapseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SynapseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpec) DeepCopyInto(out *SynapseSpec) {
	*out = *in
	in.Homeserver.DeepCopyInto(&out.Homeserver)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpec.
func (in *SynapseSpec) DeepCopy() *SynapseSpec {
	if in == nil {
		return nil
	}
	out := new(SynapseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeServerLogging) DeepCopyInto(out *SynapseSpecHomeServerLogging) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeServerLogging.
func (in *SynapseSpecHomeServerLogging) DeepCopy() *SynapseSpecHomeServerLogging {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeServerLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeServerRegistration) DeepCopyInto(out *SynapseSpecHomeServerRegistration) {
	*out = *in
	if in.AutoJoinRooms != nil {
		in, out := &in.AutoJoinRooms, &out.AutoJoinRooms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeServerRegistration.
func (in *SynapseSpecHomeServerRegistration) DeepCopy() *SynapseSpecHomeServerRegistration {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeServerRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeServerSecurity) DeepCopyInto(out *SynapseSpecHomeServerSecurity) {
	*out = *in
	if in.TrustedKeyServers != nil {
		in, out := &in.TrustedKeyServers, &out.TrustedKeyServers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeServerSecurity.
func (in *SynapseSpecHomeServerSecurity) DeepCopy() *SynapseSpecHomeServerSecurity {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeServerSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeServerUploads) DeepCopyInto(out *SynapseSpecHomeServerUploads) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeServerUploads.
func (in *SynapseSpecHomeServerUploads) DeepCopy() *SynapseSpecHomeServerUploads {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeServerUploads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeServerUrlPreview) DeepCopyInto(out *SynapseSpecHomeServerUrlPreview) {
	*out = *in
	in.Rules.DeepCopyInto(&out.Rules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeServerUrlPreview.
func (in *SynapseSpecHomeServerUrlPreview) DeepCopy() *SynapseSpecHomeServerUrlPreview {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeServerUrlPreview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeServerUrlPreviewRules) DeepCopyInto(out *SynapseSpecHomeServerUrlPreviewRules) {
	*out = *in
	in.Ip.DeepCopyInto(&out.Ip)
	in.Url.DeepCopyInto(&out.Url)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeServerUrlPreviewRules.
func (in *SynapseSpecHomeServerUrlPreviewRules) DeepCopy() *SynapseSpecHomeServerUrlPreviewRules {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeServerUrlPreviewRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeServerUrlPreviewRulesIp) DeepCopyInto(out *SynapseSpecHomeServerUrlPreviewRulesIp) {
	*out = *in
	if in.Whitelist != nil {
		in, out := &in.Whitelist, &out.Whitelist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Blacklist != nil {
		in, out := &in.Blacklist, &out.Blacklist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeServerUrlPreviewRulesIp.
func (in *SynapseSpecHomeServerUrlPreviewRulesIp) DeepCopy() *SynapseSpecHomeServerUrlPreviewRulesIp {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeServerUrlPreviewRulesIp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeServerUrlPreviewRulesUrl) DeepCopyInto(out *SynapseSpecHomeServerUrlPreviewRulesUrl) {
	*out = *in
	if in.Whitelist != nil {
		in, out := &in.Whitelist, &out.Whitelist
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Blacklist != nil {
		in, out := &in.Blacklist, &out.Blacklist
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeServerUrlPreviewRulesUrl.
func (in *SynapseSpecHomeServerUrlPreviewRulesUrl) DeepCopy() *SynapseSpecHomeServerUrlPreviewRulesUrl {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeServerUrlPreviewRulesUrl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseSpecHomeserver) DeepCopyInto(out *SynapseSpecHomeserver) {
	*out = *in
	out.Uploads = in.Uploads
	in.Registration.DeepCopyInto(&out.Registration)
	in.UrlPreviews.DeepCopyInto(&out.UrlPreviews)
	in.Security.DeepCopyInto(&out.Security)
	out.Logging = in.Logging
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseSpecHomeserver.
func (in *SynapseSpecHomeserver) DeepCopy() *SynapseSpecHomeserver {
	if in == nil {
		return nil
	}
	out := new(SynapseSpecHomeserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynapseStatus) DeepCopyInto(out *SynapseStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynapseStatus.
func (in *SynapseStatus) DeepCopy() *SynapseStatus {
	if in == nil {
		return nil
	}
	out := new(SynapseStatus)
	in.DeepCopyInto(out)
	return out
}
